[package]
name = "screen-mask"
version = "0.1.0"
edition = "2024"

[dependencies.windows-sys]
version = "0.60.2"
features = [
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Controls",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_System_LibraryLoader",
    "Win32_Graphics_Gdi",
]
