// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package testdata

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Foo struct {
	A                    int32    `protobuf:"varint,1,opt,name=a,proto3" json:"a"`
	B                    string   `protobuf:"bytes,2,opt,name=b,proto3" json:"b"`
	C                    bool     `protobuf:"varint,3,opt,name=c,proto3" json:"c"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Foo) Reset()         { *m = Foo{} }
func (m *Foo) String() string { return proto.CompactTextString(m) }
func (*Foo) ProtoMessage()    {}
func (*Foo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *Foo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Foo.Unmarshal(m, b)
}
func (m *Foo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Foo.Marshal(b, m, deterministic)
}
func (m *Foo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Foo.Merge(m, src)
}
func (m *Foo) XXX_Size() int {
	return xxx_messageInfo_Foo.Size(m)
}
func (m *Foo) XXX_DiscardUnknown() {
	xxx_messageInfo_Foo.DiscardUnknown(m)
}

var xxx_messageInfo_Foo proto.InternalMessageInfo

func (m *Foo) GetA() int32 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *Foo) GetB() string {
	if m != nil {
		return m.B
	}
	return ""
}

func (m *Foo) GetC() bool {
	if m != nil {
		return m.C
	}
	return false
}

func init() {
	proto.RegisterType((*Foo)(nil), "testdata.Foo")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 93 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0xb1, 0x53, 0x12, 0x4b, 0x12, 0x95, 0xf4,
	0xb9, 0x98, 0xdd, 0xf2, 0xf3, 0x85, 0x78, 0xb8, 0x18, 0x13, 0x25, 0x18, 0x15, 0x18, 0x35, 0x58,
	0x83, 0x18, 0x13, 0x41, 0xbc, 0x24, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xce, 0x20, 0xc6, 0x24, 0x10,
	0x2f, 0x59, 0x82, 0x59, 0x81, 0x51, 0x83, 0x23, 0x88, 0x31, 0x39, 0x89, 0x0d, 0x6c, 0x82, 0x31,
	0x20, 0x00, 0x00, 0xff, 0xff, 0xca, 0x1d, 0x4e, 0xcf, 0x4f, 0x00, 0x00, 0x00,
}
